# Generated by Django 6.0.2 on 2026-03-31 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sitevisit_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='churnalert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_alerts', to='app.clientorganization'),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientorganization',
            name='relationship_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned'), ('reengage', 'Re-engage')], default='prospect', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='related_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.clientorganization'),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('processed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='app.clientcontact')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='app.clientorganization')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
