# Generated by Django 6.0.2 on 2026-04-24 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_churnalert_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('promotion', 'Promotion'), ('discount', 'Discount'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('seasonal', 'Seasonal')], default='promotion', max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('recipient_group', models.CharField(default='all', help_text='Slug: all | active | prospects | at_risk | org_<id>', max_length=50)),
                ('recipient_emails', models.TextField(blank=True, default='[]')),
                ('recipient_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Campaign',
                'verbose_name_plural': 'Bulk Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
