# Generated by Django 6.0.2 on 2026-04-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bulkcampaign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='EmailMessageContacts',
        ),
    ]
