"""
seed_competitors.py
===================
Management command — seeds 100+ realistic Zimbabwean training institution
competitors into the Competitor model.

Save as:  app/management/commands/seed_competitors.py
Run with: python manage.py seed_competitors
          python manage.py seed_competitors --clear   # wipe existing first
"""

from django.core.management.base import BaseCommand
from app.models import Competitor


COMPETITORS = [
    # ─── TIER 1 — HIGH THREAT (7.0 – 9.5) ───────────────────────────────────
    {
        "name": "Zimbabwe Open University (ZOU)",
        "service_focus": "Distance and open learning; undergraduate and postgraduate programmes in education, commerce, law, and technology. Large-scale corporate training partnerships.",
        "pricing_notes": "Subsidised government rates. Certificate courses from USD 120–350. Degree programmes USD 600–1,800/year.",
        "strengths": "Largest distance-learning footprint in Zimbabwe; government backing; 10 regional centres; strong brand recognition; accredited by ZIMCHE.",
        "weaknesses": "Slow curriculum updates; limited interactivity in online delivery; perceived lower prestige than contact institutions.",
        "threat_level": 9.2,
        "market_share_estimate": 14.5,
    },
    {
        "name": "University of Zimbabwe (UZ) — Continuing Education",
        "service_focus": "Professional short courses, executive education, ICT training, and postgraduate diplomas. Targets working professionals and corporates.",
        "pricing_notes": "Short courses USD 200–800. Executive programmes USD 1,500–4,000. Some employer-sponsored cohorts.",
        "strengths": "Oldest and most prestigious university in Zimbabwe; strong alumni network; research-backed content; ZIMCHE-accredited.",
        "weaknesses": "Bureaucratic enrollment process; limited evening and weekend offerings; aging infrastructure at main campus.",
        "threat_level": 9.0,
        "market_share_estimate": 11.2,
    },
    {
        "name": "Speciss College",
        "service_focus": "IT, networking, cybersecurity, software development, Microsoft and Cisco certifications. One of the largest private ICT training providers.",
        "pricing_notes": "CISCO CCNA USD 450–600. Microsoft certs USD 350–550. Diploma programmes USD 1,200–2,500.",
        "strengths": "Authorised Cisco and Microsoft training partner; strong industry linkages; modern labs; well-known brand in corporate ICT training.",
        "weaknesses": "Predominantly Harare-based; limited soft-skills and management content; high staff turnover reported.",
        "threat_level": 8.8,
        "market_share_estimate": 9.0,
    },
    {
        "name": "Institute of Chartered Accountants of Zimbabwe (ICAZ) Training",
        "service_focus": "Accounting, auditing, tax, IFRS, and financial management. CPD programmes for finance professionals across all sectors.",
        "pricing_notes": "CPD seminars USD 80–250/day. Full CA training pathway USD 2,000–5,000 over programme duration.",
        "strengths": "Professional body authority; internationally recognised CA qualification; strong corporate client base in banking and finance.",
        "weaknesses": "Narrow subject focus (finance only); limited digital delivery options; mainly Harare and Bulawayo.",
        "threat_level": 8.5,
        "market_share_estimate": 7.8,
    },
    {
        "name": "Midlands State University (MSU) — Outreach & Training",
        "service_focus": "Management development, agriculture, ICT, and technical vocational training. Extensive rural and peri-urban outreach programmes.",
        "pricing_notes": "Short courses USD 100–400. Diploma programmes USD 500–1,500. Government partnership rates available.",
        "strengths": "Largest university by student enrolment; strong provincial presence; diverse programme portfolio; affordable pricing.",
        "weaknesses": "Quality inconsistency across faculties; limited postgraduate research standing; infrastructure challenges at satellite centres.",
        "threat_level": 8.3,
        "market_share_estimate": 8.1,
    },
    {
        "name": "Harare Institute of Technology (HIT) — Executive Training",
        "service_focus": "Technology management, innovation, entrepreneurship, and applied sciences training for industry professionals.",
        "pricing_notes": "Short courses USD 180–500. Technology management programmes USD 1,000–3,000.",
        "strengths": "Government-designated technology university; strong engineering and tech focus; industry-embedded curriculum; national mandate.",
        "weaknesses": "Limited management and soft-skills depth; smaller alumni network than UZ; primarily serves engineering sectors.",
        "threat_level": 8.0,
        "market_share_estimate": 5.5,
    },
    {
        "name": "IPMZ — Institute of People Management Zimbabwe",
        "service_focus": "HR management, industrial relations, labour law, payroll, and organisational development. Zimbabwe's leading HR professional body training arm.",
        "pricing_notes": "Certificate in HR USD 600–900. Diploma USD 1,200–1,800. Short workshops USD 120–300/day.",
        "strengths": "Sole recognised HR professional body in Zimbabwe; mandatory CPD for HR practitioners; wide membership base; well-structured curriculum.",
        "weaknesses": "Slow to adopt e-learning; content sometimes lags behind global HR trends; limited cross-sector diversification.",
        "threat_level": 7.9,
        "market_share_estimate": 6.2,
    },
    {
        "name": "National University of Science and Technology (NUST) — CMED",
        "service_focus": "Management, engineering, built environment, and applied sciences professional development. Centre for Management and Executive Development (CMED).",
        "pricing_notes": "Executive courses USD 300–900. Full management programmes USD 1,500–3,500.",
        "strengths": "Strong STEM reputation; good corporate partnerships in Bulawayo and Matabeleland; ZIMCHE-accredited; growing online capability.",
        "weaknesses": "Geographically concentrated in Bulawayo; perceived as less prestigious than UZ in management disciplines.",
        "threat_level": 7.7,
        "market_share_estimate": 5.8,
    },
    {
        "name": "BancABC Zimbabwe — Learning & Development (External Arm)",
        "service_focus": "Financial services training, banking operations, credit analysis, anti-money laundering, and fintech for the banking sector.",
        "pricing_notes": "Sector-specific. External packages USD 400–1,200 per programme. Primarily consortium-funded.",
        "strengths": "Deep banking sector expertise; regulatory alignment; credibility with financial institutions; RBZ-preferred content.",
        "weaknesses": "Very narrow sector focus; not widely accessible outside banking; limited brand recognition in non-finance sectors.",
        "threat_level": 7.5,
        "market_share_estimate": 3.2,
    },
    {
        "name": "ZIMDEF-Accredited Training Consortium",
        "service_focus": "Vocational and technical skills, trades, entrepreneurship, and TVET programmes funded or co-funded through ZIMDEF levies.",
        "pricing_notes": "Heavily subsidised or free for ZIMDEF levy-paying companies. Direct-cost programmes USD 80–300.",
        "strengths": "ZIMDEF funding makes training nearly free for eligible companies; wide geographic spread; government mandate.",
        "weaknesses": "Bureaucratic ZIMDEF claims process; variable quality across consortium members; limited management-level content.",
        "threat_level": 7.3,
        "market_share_estimate": 6.5,
    },

    # ─── TIER 2 — MEDIUM-HIGH THREAT (5.0 – 6.9) ────────────────────────────
    {
        "name": "FORMAT Zimbabwe",
        "service_focus": "Accounting technician training (AAT), bookkeeping, payroll, and tax compliance. Popular among SMEs and NGOs.",
        "pricing_notes": "AAT Foundation USD 350–550. Diploma levels USD 700–1,100. In-house packages negotiable.",
        "strengths": "AAT Zimbabwe partner; affordable pricing; practical approach; strong SME market penetration.",
        "weaknesses": "Limited management and leadership content; small team; primarily Harare-based.",
        "threat_level": 6.8,
        "market_share_estimate": 3.5,
    },
    {
        "name": "Celebration College of Business",
        "service_focus": "Business administration, accounting, marketing, secretarial studies, and HR diplomas for working professionals.",
        "pricing_notes": "Diplomas USD 400–900/year. Short certificates USD 150–300.",
        "strengths": "Affordable fees; flexible scheduling; well-established in Harare's suburban market.",
        "weaknesses": "Limited brand reach outside Harare; no recognised professional body affiliation; dated facilities.",
        "threat_level": 6.5,
        "market_share_estimate": 2.8,
    },
    {
        "name": "Triumph Training College",
        "service_focus": "Office administration, customer service, communication skills, and front-line staff development.",
        "pricing_notes": "Short courses USD 80–200. Certificate programmes USD 250–500.",
        "strengths": "Quick turnaround training; competitive pricing; targets entry- and mid-level staff widely sought by NGOs.",
        "weaknesses": "Limited executive-level content; small footprint; not accredited by HEXCO or ZIMCHE for all programmes.",
        "threat_level": 6.3,
        "market_share_estimate": 2.1,
    },
    {
        "name": "Zimbabwe Institute of Management (ZIM)",
        "service_focus": "Management development, strategic planning, project management, and leadership programmes.",
        "pricing_notes": "Management diplomas USD 800–1,500. Short workshops USD 150–400.",
        "strengths": "Long-standing management training brand; good network in parastatal sector; practical facilitation style.",
        "weaknesses": "Outdated marketing; limited digital presence; faculty not always current with global management trends.",
        "threat_level": 6.2,
        "market_share_estimate": 3.0,
    },
    {
        "name": "Bindura University of Science Education (BUSE) — CPD",
        "service_focus": "Science, technology, and education CPD. Teacher development programmes and STEM workplace training.",
        "pricing_notes": "CPD workshops USD 100–300. Certificate programmes USD 400–800.",
        "strengths": "Niche STEM and education focus; government teacher training contracts; ZIMCHE-accredited.",
        "weaknesses": "Limited corporate market penetration; mainly serves education sector; Bindura location limits accessibility.",
        "threat_level": 6.0,
        "market_share_estimate": 2.4,
    },
    {
        "name": "Solusi University — Continuing Education",
        "service_focus": "Business, theology, education, and health CPD. Seventh-day Adventist-affiliated; strong ethical leadership programmes.",
        "pricing_notes": "Certificate courses USD 200–500. Diploma programmes USD 600–1,200.",
        "strengths": "Strong values-based leadership content; accredited by ZIMCHE; good reputation in faith-based organisations.",
        "weaknesses": "Religious affiliation limits secular corporate market; remote location in Matabeleland North.",
        "threat_level": 5.8,
        "market_share_estimate": 1.9,
    },
    {
        "name": "Africa University — Institute for Continuing Education",
        "service_focus": "Pan-African leadership, governance, public health, agriculture, and business management.",
        "pricing_notes": "Short courses USD 250–700. Postgraduate programmes USD 1,500–3,500.",
        "strengths": "Pan-African brand; Methodist Church backing; ZIMCHE and international accreditation; strong NGO and donor client base.",
        "weaknesses": "Mutare location is inconvenient for Harare-based corporates; small training centre capacity.",
        "threat_level": 5.7,
        "market_share_estimate": 2.0,
    },
    {
        "name": "ProPharma Training Institute",
        "service_focus": "Pharmaceutical, healthcare management, clinical skills, and regulatory compliance for health sector professionals.",
        "pricing_notes": "Clinical skills workshops USD 150–400. Management courses USD 300–700.",
        "strengths": "Deep health sector expertise; MoHCC-recognised content; growing demand from hospitals and NGOs.",
        "weaknesses": "Very narrow sector focus; limited management depth; small team.",
        "threat_level": 5.5,
        "market_share_estimate": 1.5,
    },
    {
        "name": "Zimbabwe School of Mines — Training Division",
        "service_focus": "Mining operations, occupational health and safety, environmental management, and engineering skills for the mining sector.",
        "pricing_notes": "Safety courses USD 150–350. Technical skills USD 300–800. In-mine programmes negotiated per company.",
        "strengths": "Mining sector authority; MHTE-accredited; essential regulatory compliance training; direct client base in major mines.",
        "weaknesses": "Single-sector focus; Bulawayo and mine-site based; limited corporate management content.",
        "threat_level": 5.4,
        "market_share_estimate": 2.2,
    },
    {
        "name": "Earthworm Training Centre",
        "service_focus": "Agriculture, agribusiness, irrigation, and rural enterprise development. Targets farmers, cooperatives, and agri-corporates.",
        "pricing_notes": "Farmer training USD 50–150. Agribusiness management USD 200–500.",
        "strengths": "Niche agri expertise; donor-funded reach; community development credibility; bilingual delivery (English/Shona).",
        "weaknesses": "Very niche market; minimal urban corporate relevance; low profit-margin model.",
        "threat_level": 5.2,
        "market_share_estimate": 1.3,
    },
    {
        "name": "CUT — Chinhoyi University of Technology CPD",
        "service_focus": "Technology, hospitality, engineering, and agriculture professional development. Serves Mashonaland West province heavily.",
        "pricing_notes": "Short courses USD 120–400. Certificate programmes USD 400–900.",
        "strengths": "Strong provincial presence; hospitality sector reputation; ZIMCHE-accredited; government support.",
        "weaknesses": "Limited brand recognition in Harare; infrastructure constraints; small CPD unit.",
        "threat_level": 5.0,
        "market_share_estimate": 1.8,
    },

    # ─── TIER 3 — MEDIUM THREAT (3.0 – 4.9) ─────────────────────────────────
    {
        "name": "Women's University in Africa (WUA) — Training",
        "service_focus": "Gender-inclusive management, entrepreneurship, health, and education CPD. Primarily targets women professionals.",
        "pricing_notes": "Certificate courses USD 180–450. Diploma programmes USD 500–1,000.",
        "strengths": "Unique gender-focused positioning; ZIMCHE-accredited; strong NGO and donor partnerships; growing enrolment.",
        "weaknesses": "Niche audience limits market size; limited infrastructure; Harare-centric.",
        "threat_level": 4.8,
        "market_share_estimate": 1.6,
    },
    {
        "name": "Great Zimbabwe University (GZU) — Outreach",
        "service_focus": "Humanities, social sciences, education, and management CPD for Masvingo and Midlands provinces.",
        "pricing_notes": "Short courses USD 100–350. Certificate programmes USD 350–800.",
        "strengths": "Strong regional presence; ZIMCHE-accredited; cultural heritage sector expertise; affordable fees.",
        "weaknesses": "Limited corporate penetration; Masvingo location disadvantage for Harare market; small CPD unit.",
        "threat_level": 4.6,
        "market_share_estimate": 1.7,
    },
    {
        "name": "Progress Training Institute",
        "service_focus": "Secretarial studies, office management, customer service, and basic computing for administrative professionals.",
        "pricing_notes": "Certificate USD 150–350. Diploma USD 300–600.",
        "strengths": "Affordable; flexible evening classes; practical skills focus; established in Harare's Glen View area.",
        "weaknesses": "No professional body accreditation; limited to entry-level content; small scale.",
        "threat_level": 4.5,
        "market_share_estimate": 1.0,
    },
    {
        "name": "Morgenster College",
        "service_focus": "Agriculture, health, and community development training in Masvingo province. Reformed Church of Zimbabwe-affiliated.",
        "pricing_notes": "Community programmes USD 30–100. Formal courses USD 200–500.",
        "strengths": "Deep rural community trust; mission-driven mandate; bilingual delivery; strong NGO partnerships.",
        "weaknesses": "Very rural focus; limited corporate relevance; Morgenster location is remote.",
        "threat_level": 4.3,
        "market_share_estimate": 0.9,
    },
    {
        "name": "ZimTech Training Solutions",
        "service_focus": "Graphic design, web development, digital marketing, and social media management for SMEs and entrepreneurs.",
        "pricing_notes": "Short courses USD 100–300. Bootcamps USD 350–600.",
        "strengths": "Modern digital skills content; affordable; growing demand from SME sector; entrepreneurship focus.",
        "weaknesses": "Small team; limited corporate client base; no formal accreditation.",
        "threat_level": 4.2,
        "market_share_estimate": 0.8,
    },
    {
        "name": "Integrity Training College",
        "service_focus": "Ethics, governance, compliance, anti-corruption, and public sector management.",
        "pricing_notes": "Workshops USD 120–300/day. Certificate programmes USD 400–700.",
        "strengths": "Growing compliance market; ZACC and public sector alignment; specialist positioning.",
        "weaknesses": "Niche market; small team; limited private sector penetration.",
        "threat_level": 4.1,
        "market_share_estimate": 0.7,
    },
    {
        "name": "Stewart Institute of Management",
        "service_focus": "General management, supervisory skills, and team leadership for mid-level managers.",
        "pricing_notes": "Supervisory skills USD 120–250. Management programmes USD 400–800.",
        "strengths": "Practical, hands-on facilitation style; affordable; good mid-market positioning.",
        "weaknesses": "Weak brand visibility; limited digital marketing; no strong professional body link.",
        "threat_level": 4.0,
        "market_share_estimate": 0.9,
    },
    {
        "name": "Ruzivo Digital Learning",
        "service_focus": "Digital literacy, e-learning content development, and EdTech solutions for schools and corporates.",
        "pricing_notes": "Digital literacy packages USD 80–200. E-learning development project-based pricing.",
        "strengths": "Innovative EdTech approach; UNICEF and donor support; scalable digital delivery.",
        "weaknesses": "Early-stage company; limited brand recognition in corporate training market; revenue model still maturing.",
        "threat_level": 3.9,
        "market_share_estimate": 0.5,
    },
    {
        "name": "Lupane State University — CPD Unit",
        "service_focus": "Agribusiness, natural resources management, and rural entrepreneurship in Matabeleland North.",
        "pricing_notes": "Certificate courses USD 100–300. Diploma programmes USD 350–700.",
        "strengths": "Niche natural resources expertise; government-funded; ZIMCHE-accredited; serves underserved Matabeleland region.",
        "weaknesses": "Remote location; very limited corporate market; small team.",
        "threat_level": 3.8,
        "market_share_estimate": 0.8,
    },
    {
        "name": "Pan Africa Christian College",
        "service_focus": "Theology, leadership, and community development. Faith-based professional development for NGO and church leaders.",
        "pricing_notes": "Leadership programmes USD 150–400. Certificate courses USD 100–250.",
        "strengths": "Strong faith-sector network; affordable; values-based leadership content.",
        "weaknesses": "Very niche audience; limited secular corporate market appeal; small scale.",
        "threat_level": 3.7,
        "market_share_estimate": 0.4,
    },
    {
        "name": "Apex Vocational Training Centre",
        "service_focus": "Welding, plumbing, electrical installation, and automotive trades. HEXCO-registered TVET provider.",
        "pricing_notes": "Trade certificates USD 300–600. Short skills courses USD 100–250.",
        "strengths": "HEXCO accreditation; hands-on practical training; strong demand for artisan skills.",
        "weaknesses": "Trades focus limits corporate management market; ageing equipment; Chitungwiza location.",
        "threat_level": 3.6,
        "market_share_estimate": 0.7,
    },
    {
        "name": "Harare Polytechnic — Industry Training",
        "service_focus": "Engineering, ICT, catering, and applied sciences continuing education for industry professionals.",
        "pricing_notes": "HEXCO certificate programmes USD 250–500. Short courses USD 80–200.",
        "strengths": "Government institution; HEXCO-accredited; practical workshop facilities; affordable fees.",
        "weaknesses": "Bureaucratic; limited corporate-facing marketing; dated curriculum in some areas.",
        "threat_level": 3.5,
        "market_share_estimate": 1.2,
    },
    {
        "name": "Bulawayo Polytechnic — CPD",
        "service_focus": "Engineering, business, ICT, and trades continuing education in Matabeleland region.",
        "pricing_notes": "Certificate courses USD 200–450. Short skills USD 80–180.",
        "strengths": "HEXCO-accredited; strong Bulawayo market presence; practical focus; government backing.",
        "weaknesses": "Bulawayo-centric; limited Harare reach; bureaucratic processes.",
        "threat_level": 3.4,
        "market_share_estimate": 1.1,
    },
    {
        "name": "Gweru Teachers College — Professional Development",
        "service_focus": "Education CPD, teacher upgrading, and curriculum development for Midlands province.",
        "pricing_notes": "Teacher upgrading USD 150–400. Workshops USD 80–200.",
        "strengths": "MoPSE-linked; ZIMCHE-accredited; trusted by education sector; affordable.",
        "weaknesses": "Single-sector (education) focus; limited corporate relevance; Gweru location.",
        "threat_level": 3.3,
        "market_share_estimate": 0.6,
    },
    {
        "name": "CABS Business School (informal training arm)",
        "service_focus": "Financial literacy, mortgage and banking product training, SME finance management.",
        "pricing_notes": "Financial literacy workshops USD 50–150. SME finance programmes USD 200–400.",
        "strengths": "Strong CABS banking brand; practical financial content; existing client relationships.",
        "weaknesses": "Not a dedicated training institution; narrow product focus; limited facilitator depth.",
        "threat_level": 3.2,
        "market_share_estimate": 0.5,
    },
    {
        "name": "Harvest House Business School",
        "service_focus": "Entrepreneurship, SME management, and business start-up coaching for emerging entrepreneurs.",
        "pricing_notes": "Entrepreneurship bootcamps USD 100–250. Mentorship programmes USD 200–500.",
        "strengths": "Entrepreneur community credibility; practical focus; affordable; Harare CBD presence.",
        "weaknesses": "Small team; no formal accreditation; limited corporate market relevance.",
        "threat_level": 3.1,
        "market_share_estimate": 0.4,
    },
    {
        "name": "Zimbabwe National Chamber of Commerce (ZNCC) Training",
        "service_focus": "Trade facilitation, customs, export-import, and business regulatory compliance training.",
        "pricing_notes": "Compliance workshops USD 100–250. Trade programmes USD 200–500.",
        "strengths": "Chamber membership credibility; business regulatory content alignment; national network.",
        "weaknesses": "Not a dedicated training provider; limited curriculum depth; event-based rather than programme-based.",
        "threat_level": 3.0,
        "market_share_estimate": 0.6,
    },

    # ─── TIER 4 — LOW-MEDIUM THREAT (1.5 – 2.9) ──────────────────────────────
    {
        "name": "Kuwadzana Vocational Training Centre",
        "service_focus": "Dressmaking, hairdressing, carpentry, and basic computing for community-level learners.",
        "pricing_notes": "Certificate programmes USD 80–180.",
        "strengths": "Community accessibility; low-cost; government-subsidised.",
        "weaknesses": "No corporate market relevance; very basic content; aging equipment.",
        "threat_level": 2.9,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Mabelreign Teachers College",
        "service_focus": "Primary teacher education and education CPD for Harare region.",
        "pricing_notes": "Teacher upgrading USD 100–300.",
        "strengths": "MoPSE-accredited; Harare location; established institution.",
        "weaknesses": "Education-sector only; no corporate training offering.",
        "threat_level": 2.8,
        "market_share_estimate": 0.4,
    },
    {
        "name": "Seke Teachers College",
        "service_focus": "Teacher education and professional development for primary and secondary school teachers.",
        "pricing_notes": "CPD workshops USD 80–200.",
        "strengths": "MoPSE trust; affordable; bilingual delivery.",
        "weaknesses": "Single-sector focus; Chitungwiza location; limited corporate relevance.",
        "threat_level": 2.7,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Kushinga-Phikelela Polytechnic",
        "service_focus": "Agriculture, horticulture, and food processing skills training in Marondera.",
        "pricing_notes": "Certificate programmes USD 150–350.",
        "strengths": "Government support; agri-sector niche; HEXCO-accredited.",
        "weaknesses": "Very rural focus; Marondera location; limited corporate management content.",
        "threat_level": 2.6,
        "market_share_estimate": 0.4,
    },
    {
        "name": "Marondera College of Agriculture",
        "service_focus": "Commercial farming, agri-business management, and irrigation technology.",
        "pricing_notes": "Agri-business courses USD 150–400.",
        "strengths": "Specialised agri content; practical farm-based learning; ZIMDEF-eligible.",
        "weaknesses": "Narrow sector appeal; Marondera location; small team.",
        "threat_level": 2.5,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Msasa Artisan Training Trust",
        "service_focus": "Metalwork, welding, and construction artisan skills for the construction industry.",
        "pricing_notes": "Trade skills USD 200–400.",
        "strengths": "Practical skills; construction sector demand; affordable.",
        "weaknesses": "No management content; small scale; Msasa Industrial area only.",
        "threat_level": 2.4,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Hillcrest College Zimbabwe",
        "service_focus": "Secondary and A-level education with some career guidance and business basics for school leavers.",
        "pricing_notes": "School-to-work transition USD 100–200.",
        "strengths": "School-leaver market; Harare location; some corporate internship placements.",
        "weaknesses": "Not a formal professional training institution; no CPD programmes.",
        "threat_level": 2.3,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Hillside Teachers College",
        "service_focus": "Secondary school teacher education and in-service CPD for Bulawayo region.",
        "pricing_notes": "In-service training USD 80–200.",
        "strengths": "MoPSE-accredited; Bulawayo presence; affordable.",
        "weaknesses": "Education sector only; very limited corporate market.",
        "threat_level": 2.2,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Mkoba Teachers College",
        "service_focus": "Primary and secondary teacher development in Gweru, Midlands.",
        "pricing_notes": "CPD workshops USD 60–180.",
        "strengths": "MoPSE trust; Midlands regional coverage; bilingual.",
        "weaknesses": "Education only; Gweru location; no corporate training.",
        "threat_level": 2.1,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Madziwa College of Education",
        "service_focus": "Teacher education and rural community development in Mashonaland Central.",
        "pricing_notes": "Teacher CPD USD 60–150.",
        "strengths": "Rural community trust; MoPSE-accredited; bilingual delivery.",
        "weaknesses": "Very remote; no corporate relevance; limited programme range.",
        "threat_level": 2.0,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Nyadire Teachers College",
        "service_focus": "Teacher education and community health CPD in Mutoko district.",
        "pricing_notes": "CPD USD 50–140.",
        "strengths": "Methodist Church backing; community trust; bilingual.",
        "weaknesses": "Remote location; education-only; no corporate training capacity.",
        "threat_level": 1.9,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Gandanzara Teachers College",
        "service_focus": "Primary teacher education in Manicaland province.",
        "pricing_notes": "In-service CPD USD 50–130.",
        "strengths": "MoPSE-accredited; Manicaland coverage; affordable.",
        "weaknesses": "Rural location; education only; very limited scope.",
        "threat_level": 1.8,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Mutare Polytechnic — Short Courses",
        "service_focus": "Business, ICT, and trades short courses in Manicaland.",
        "pricing_notes": "Short courses USD 80–200.",
        "strengths": "HEXCO-accredited; Mutare market presence; practical focus.",
        "weaknesses": "Small CPD unit; limited corporate marketing; Mutare location.",
        "threat_level": 1.7,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Gwanda Community College",
        "service_focus": "Basic business, computing, and trades for Matabeleland South communities.",
        "pricing_notes": "Certificate courses USD 60–160.",
        "strengths": "Community access; affordable; Matabeleland South presence.",
        "weaknesses": "Very small scale; no accreditation; limited programme range.",
        "threat_level": 1.6,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Beit Bridge Business Hub Training",
        "service_focus": "Cross-border trade, customs, and small business management for Limpopo corridor traders.",
        "pricing_notes": "Trade workshops USD 50–150.",
        "strengths": "Unique border-town market; bilingual (English/Ndebele); practical focus.",
        "weaknesses": "Very niche; Beit Bridge only; no formal accreditation.",
        "threat_level": 1.5,
        "market_share_estimate": 0.1,
    },

    # ─── TIER 5 — EMERGING / NICHE / LOW THREAT (0.5 – 1.4) ─────────────────
    {
        "name": "Takura Trust Training",
        "service_focus": "Livelihoods, financial inclusion, and cooperative management for rural communities.",
        "pricing_notes": "Donor-funded; minimal direct fees.",
        "strengths": "NGO-backed; deep rural reach; community development credibility.",
        "weaknesses": "No corporate market; very small; dependent on donor funding.",
        "threat_level": 1.4,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Africaworks Skills Academy",
        "service_focus": "Digital skills, freelancing, and remote work preparation for youth.",
        "pricing_notes": "Bootcamps USD 80–200.",
        "strengths": "Modern skills; youth market; low cost; online-ready content.",
        "weaknesses": "Very new; limited brand recognition; small team.",
        "threat_level": 1.3,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Victoria Falls School of Tourism",
        "service_focus": "Tourism management, hospitality, and conservation education in Hwange/Victoria Falls area.",
        "pricing_notes": "Certificate courses USD 200–500.",
        "strengths": "Tourism hub location; specialist niche; growing demand.",
        "weaknesses": "Remote from Harare; very niche; small scale.",
        "threat_level": 1.2,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Masvingo School of Business",
        "service_focus": "Accounting, business administration, and entrepreneurship for Masvingo region.",
        "pricing_notes": "Certificate programmes USD 150–350.",
        "strengths": "Masvingo market presence; affordable; practical focus.",
        "weaknesses": "No accreditation; small team; limited brand reach.",
        "threat_level": 1.1,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Zimcare Trust Training Centre",
        "service_focus": "Disability-inclusive vocational skills, tailoring, and crafts for persons with disabilities.",
        "pricing_notes": "Subsidised/free for PWD beneficiaries.",
        "strengths": "Unique inclusivity mandate; NGO credibility; donor support.",
        "weaknesses": "No corporate training relevance; very niche beneficiary group.",
        "threat_level": 1.0,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Simukai Child Protection Training",
        "service_focus": "Child safeguarding, social work CPD, and community development for NGO staff.",
        "pricing_notes": "Workshops USD 80–180.",
        "strengths": "NGO sector credibility; child protection regulatory alignment.",
        "weaknesses": "Very narrow sector; NGO-only; no corporate market.",
        "threat_level": 0.9,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Ruwa Community College",
        "service_focus": "Basic computing, business administration, and tailoring for Ruwa/Epworth communities.",
        "pricing_notes": "Certificate courses USD 60–150.",
        "strengths": "Community affordability; Ruwa/Epworth market; practical.",
        "weaknesses": "No accreditation; very small scale; no corporate relevance.",
        "threat_level": 0.8,
        "market_share_estimate": 0.1,
    },
    {
        "name": "UNFPA Zimbabwe — Capacity Building (external)",
        "service_focus": "Reproductive health, gender, and data management training for public health workers.",
        "pricing_notes": "Fully donor-funded.",
        "strengths": "UN credibility; free for beneficiaries; government partnerships.",
        "weaknesses": "Not a commercial training institution; cannot be contracted by private sector.",
        "threat_level": 0.7,
        "market_share_estimate": 0.0,
    },
    {
        "name": "Empowerment Skills Centre (Chitungwiza)",
        "service_focus": "Hair and beauty, dressmaking, and basic entrepreneurship for youth in Chitungwiza.",
        "pricing_notes": "Certificate USD 50–120.",
        "strengths": "Community access; affordable; growing youth market.",
        "weaknesses": "No formal accreditation; very small; limited to lifestyle skills.",
        "threat_level": 0.6,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Zim Youth Skills Hub",
        "service_focus": "Life skills, job readiness, and basic digital literacy for school leavers.",
        "pricing_notes": "Free or subsidised (donor-funded).",
        "strengths": "Youth development mission; community credibility; growing donor support.",
        "weaknesses": "No revenue model; not a corporate competitor; very early stage.",
        "threat_level": 0.5,
        "market_share_estimate": 0.0,
    },

    # ─── ADDITIONAL RECORDS TO REACH 100+ ────────────────────────────────────
    {
        "name": "Zimbabwe Ezekiel Guti University (ZEGU) — Outreach",
        "service_focus": "Theology, education, and business management CPD. ZAOGA-affiliated university with growing professional programmes.",
        "pricing_notes": "Certificate courses USD 150–400. Diploma USD 500–1,000.",
        "strengths": "Large ZAOGA church network provides ready client base; ZIMCHE-accredited; affordable.",
        "weaknesses": "Religious affiliation limits secular market; relatively new university status.",
        "threat_level": 5.1,
        "market_share_estimate": 1.4,
    },
    {
        "name": "Institute of Bankers of Zimbabwe (IBZ)",
        "service_focus": "Banking operations, credit management, trade finance, and financial regulation compliance CPD.",
        "pricing_notes": "Professional banking courses USD 300–700. Short seminars USD 100–250.",
        "strengths": "Banking sector authority; RBZ alignment; essential compliance training; national membership base.",
        "weaknesses": "Banking-only focus; limited SME and NGO relevance.",
        "threat_level": 7.1,
        "market_share_estimate": 4.5,
    },
    {
        "name": "Marketing Institute of Zimbabwe (MIZ)",
        "service_focus": "Marketing management, brand strategy, digital marketing, and sales CPD.",
        "pricing_notes": "Diploma in marketing USD 700–1,200. Short workshops USD 120–300.",
        "strengths": "Only dedicated marketing professional body in Zimbabwe; CIM-linked content; growing digital marketing demand.",
        "weaknesses": "Small membership base; limited facilitator depth; dated marketing content in some modules.",
        "threat_level": 6.7,
        "market_share_estimate": 3.1,
    },
    {
        "name": "Construction Industry Federation of Zimbabwe (CIFOZ) Training",
        "service_focus": "Construction management, quantity surveying, occupational health and safety, and project management.",
        "pricing_notes": "Safety training USD 150–300. Management programmes USD 400–800.",
        "strengths": "Industry federation authority; regulatory OHS compliance training; direct construction sector client base.",
        "weaknesses": "Single-sector focus; limited management depth beyond construction.",
        "threat_level": 5.6,
        "market_share_estimate": 2.0,
    },
    {
        "name": "Employers' Confederation of Zimbabwe (EMCOZ) Training",
        "service_focus": "Labour relations, employment law, collective bargaining, and HR compliance for employers.",
        "pricing_notes": "Labour relations workshops USD 150–350. HR compliance USD 200–400.",
        "strengths": "Employer-body credibility; labour law content alignment; NEC/MoLSS-aligned training.",
        "weaknesses": "Employer-facing only; limited management and leadership content; event-driven model.",
        "threat_level": 5.9,
        "market_share_estimate": 2.5,
    },
    {
        "name": "Public Sector Management Institute (PSMI)",
        "service_focus": "Public administration, policy analysis, governance, and public finance management for civil servants.",
        "pricing_notes": "Government-subsidised. Some open courses USD 200–500.",
        "strengths": "Government mandate; CSSC-accredited; deep public sector network; essential for parastatal clients.",
        "weaknesses": "Government bureaucracy; limited private sector relevance; underfunded.",
        "threat_level": 6.4,
        "market_share_estimate": 3.8,
    },
    {
        "name": "Retail Association of Zimbabwe (RAZ) Training",
        "service_focus": "Retail operations, merchandising, supply chain, and customer service for retail sector staff.",
        "pricing_notes": "Retail skills workshops USD 80–200. Management programmes USD 250–500.",
        "strengths": "Retail sector authority; practical content; industry-endorsed certificates.",
        "weaknesses": "Very narrow sector; limited management and leadership depth.",
        "threat_level": 4.4,
        "market_share_estimate": 1.0,
    },
    {
        "name": "Hospitality Association of Zimbabwe (HAZ) Training",
        "service_focus": "Hotel management, food and beverage, events management, and tourism service quality.",
        "pricing_notes": "Hospitality skills USD 100–300. Management programmes USD 400–800.",
        "strengths": "Tourism sector authority; ZTA-aligned; growing post-COVID demand; practical skills focus.",
        "weaknesses": "Sector-specific; limited corporate management content; seasonal demand.",
        "threat_level": 4.7,
        "market_share_estimate": 1.3,
    },
    {
        "name": "TelOne Academy",
        "service_focus": "Telecommunications, networking, fibre technology, and ICT infrastructure training.",
        "pricing_notes": "Technical courses USD 200–500. Certification programmes USD 400–800.",
        "strengths": "National telecom brand; real infrastructure access for practical training; industry authority.",
        "weaknesses": "Limited to telecom sector; bureaucratic processes; Harare-centric.",
        "threat_level": 5.3,
        "market_share_estimate": 1.8,
    },
    {
        "name": "ZESA Holdings Training Centre",
        "service_focus": "Electrical engineering, power systems, and energy management for the electricity sector.",
        "pricing_notes": "Internal and external technical courses USD 200–600.",
        "strengths": "National utility training authority; real power infrastructure for practicals; ZINARA-aligned.",
        "weaknesses": "Primarily internal; narrow energy sector focus; slow to commercialise external training.",
        "threat_level": 4.9,
        "market_share_estimate": 1.2,
    },
    {
        "name": "CBZ Bank Learning Academy (External Arm)",
        "service_focus": "Banking operations, credit, treasury, and digital banking for financial sector professionals.",
        "pricing_notes": "Banking skills USD 300–600. External workshops USD 150–350.",
        "strengths": "Largest local bank brand; deep banking expertise; RBZ regulatory alignment.",
        "weaknesses": "Primarily internal; not widely marketed externally; finance-sector only.",
        "threat_level": 6.1,
        "market_share_estimate": 2.8,
    },
    {
        "name": "POTRAZ Training Centre",
        "service_focus": "Telecommunications regulation, spectrum management, and ICT policy for regulators and operators.",
        "pricing_notes": "Regulatory training USD 200–500.",
        "strengths": "Regulatory authority; essential compliance content; growing ICT sector demand.",
        "weaknesses": "Very niche regulatory focus; small team; not widely commercially marketed.",
        "threat_level": 3.9,
        "market_share_estimate": 0.5,
    },
    {
        "name": "Econet Wireless — EcoSchool / Training Arm",
        "service_focus": "Digital technology, mobile commerce, e-learning, and fintech skills. Primarily internal but some external programmes.",
        "pricing_notes": "Corporate digital skills USD 200–500.",
        "strengths": "Leading telecom brand; digital infrastructure; EcoCash fintech expertise; national reach.",
        "weaknesses": "Not a dedicated training institution; primarily internal; limited external programme portfolio.",
        "threat_level": 7.0,
        "market_share_estimate": 4.0,
    },
    {
        "name": "African Leadership Institute Zimbabwe",
        "service_focus": "Leadership development, executive coaching, and strategic management for senior leaders.",
        "pricing_notes": "Executive programmes USD 1,000–3,500. Coaching USD 500–2,000.",
        "strengths": "Pan-African positioning; senior executive market focus; growing executive coaching demand.",
        "weaknesses": "Premium pricing limits market size; relatively new in Zimbabwe; small facilitator pool.",
        "threat_level": 6.6,
        "market_share_estimate": 2.3,
    },
    {
        "name": "ACCA Zimbabwe — Learning Partners Network",
        "service_focus": "ACCA qualification tuition, finance, and accounting CPD through registered tuition providers.",
        "pricing_notes": "ACCA tuition USD 500–1,500 per level. CPD workshops USD 100–300.",
        "strengths": "Globally recognised ACCA brand; strong demand in finance sector; multiple registered tuition providers.",
        "weaknesses": "Dependent on tuition partners' quality; limited management and non-finance content.",
        "threat_level": 8.1,
        "market_share_estimate": 6.0,
    },
    {
        "name": "CIMA Zimbabwe — Learning Network",
        "service_focus": "CIMA management accounting qualification tuition and CPD for finance professionals.",
        "pricing_notes": "CIMA tuition USD 600–1,800 per level. CPD USD 120–300.",
        "strengths": "Globally recognised management accounting qualification; corporate finance sector demand; strong employer endorsement.",
        "weaknesses": "Narrow finance focus; dependent on registered tuition providers; competition from ACCA.",
        "threat_level": 7.8,
        "market_share_estimate": 5.2,
    },
    {
        "name": "PricewaterhouseCoopers (PwC) Zimbabwe — Advisory & Training",
        "service_focus": "Risk, governance, IFRS, internal audit, and executive tax training for large corporates and parastatals.",
        "pricing_notes": "Premium pricing. Workshops USD 500–1,500/day. Custom programmes USD 5,000–20,000.",
        "strengths": "Big 4 brand authority; highest-quality content; trusted by boards and audit committees; international best practice.",
        "weaknesses": "Very premium pricing excludes SMEs and NGOs; not focused on broad workforce training.",
        "threat_level": 8.6,
        "market_share_estimate": 4.2,
    },
    {
        "name": "Deloitte Zimbabwe — Learning & Development",
        "service_focus": "Audit, tax, consulting, and risk management CPD for large organisations and public sector.",
        "pricing_notes": "Premium. Custom training USD 4,000–18,000 per engagement.",
        "strengths": "Big 4 authority; international content standards; strong parastatal and government relationships.",
        "weaknesses": "Premium pricing; not accessible to SMEs; project-based rather than open-enrolment model.",
        "threat_level": 8.4,
        "market_share_estimate": 3.9,
    },
    {
        "name": "Ernst & Young (EY) Zimbabwe — Training",
        "service_focus": "Tax, assurance, consulting, and transformation leadership training for corporate and government clients.",
        "pricing_notes": "Premium. Engagements USD 3,500–15,000.",
        "strengths": "Global EY brand; strong tax and assurance content; government reform programme credibility.",
        "weaknesses": "Premium pricing; limited open-enrolment offering; project-based engagements.",
        "threat_level": 8.2,
        "market_share_estimate": 3.5,
    },
    {
        "name": "KPMG Zimbabwe — Training & Advisory",
        "service_focus": "Financial management, risk, governance, and public sector reform training.",
        "pricing_notes": "Premium. Custom engagements USD 3,000–12,000.",
        "strengths": "Big 4 credibility; strong government and parastatal relationships; international content.",
        "weaknesses": "Premium pricing; not accessible to broad market; limited open courses.",
        "threat_level": 8.3,
        "market_share_estimate": 3.7,
    },
    {
        "name": "SBZ Consulting & Training",
        "service_focus": "Project management (PMP prep), Agile, Scrum, and PMO setup for IT and engineering professionals.",
        "pricing_notes": "PMP prep USD 400–700. Agile/Scrum USD 250–500.",
        "strengths": "Growing project management demand; PMI-aligned content; practical facilitation.",
        "weaknesses": "Small team; limited brand visibility; no physical training centre.",
        "threat_level": 4.2,
        "market_share_estimate": 0.8,
    },
    {
        "name": "Digital Futures Zimbabwe",
        "service_focus": "Data analytics, Python, AI fundamentals, and digital transformation for corporate teams.",
        "pricing_notes": "Data analytics bootcamps USD 300–600. Corporate workshops USD 400–900.",
        "strengths": "Cutting-edge curriculum; growing data skills demand; strong tech-sector credibility.",
        "weaknesses": "Very new; small team; limited track record; premium pricing for Zimbabwe market.",
        "threat_level": 5.0,
        "market_share_estimate": 0.6,
    },
    {
        "name": "Prosper Africa Training Hub",
        "service_focus": "US-USAID-aligned trade, investment facilitation, and agribusiness management training.",
        "pricing_notes": "Donor-funded; minimal fees for beneficiaries.",
        "strengths": "USAID funding and credibility; trade facilitation expertise; regional network.",
        "weaknesses": "Dependent on donor cycles; not commercially self-sustaining; niche trade focus.",
        "threat_level": 3.5,
        "market_share_estimate": 0.4,
    },
    {
        "name": "Chartered Institute of Logistics and Transport (CILT) Zimbabwe",
        "service_focus": "Logistics, supply chain management, transport planning, and warehousing CPD.",
        "pricing_notes": "Certificate programmes USD 400–800. Short workshops USD 120–280.",
        "strengths": "International CILT brand; growing logistics sector demand; professional body authority.",
        "weaknesses": "Niche logistics focus; small Zimbabwe chapter; limited facilitator pool.",
        "threat_level": 5.5,
        "market_share_estimate": 1.6,
    },
    {
        "name": "Real Estate Institute of Zimbabwe (REIZ) Training",
        "service_focus": "Property valuation, estate agency, property management, and real estate law CPD.",
        "pricing_notes": "Certificate programmes USD 400–800. Short courses USD 150–350.",
        "strengths": "Only professional body for real estate in Zimbabwe; regulatory licensing alignment; growing property market demand.",
        "weaknesses": "Very narrow sector; small membership; limited beyond property professionals.",
        "threat_level": 4.3,
        "market_share_estimate": 0.9,
    },
    {
        "name": "Institute of Internal Auditors Zimbabwe (IIA-Z)",
        "service_focus": "Internal audit, risk management, CIA exam preparation, and governance CPD.",
        "pricing_notes": "CIA prep USD 500–900. Risk workshops USD 150–350.",
        "strengths": "International IIA brand; growing internal audit demand post-COVID; professional body authority.",
        "weaknesses": "Niche audit focus; small Zimbabwe chapter; limited open-enrolment courses.",
        "threat_level": 5.8,
        "market_share_estimate": 2.1,
    },
    {
        "name": "Health Professions Authority (HPA) Zimbabwe — CPD",
        "service_focus": "Mandatory CPD for doctors, nurses, pharmacists, and allied health professionals.",
        "pricing_notes": "CPD workshops USD 80–200.",
        "strengths": "Regulatory mandate makes attendance compulsory; large health professional base; MoHCC alignment.",
        "weaknesses": "Health sector only; not commercially driven; quality inconsistency.",
        "threat_level": 4.6,
        "market_share_estimate": 1.5,
    },
    {
        "name": "Practical Training Solutions Zimbabwe",
        "service_focus": "Supervisory management, team building, and front-line leadership for manufacturing and mining sectors.",
        "pricing_notes": "Supervisory skills USD 150–300. Team building USD 200–500.",
        "strengths": "Practical facilitation style; manufacturing and mining sector experience; competitive pricing.",
        "weaknesses": "Small boutique firm; limited brand visibility; no formal accreditation.",
        "threat_level": 4.0,
        "market_share_estimate": 0.7,
    },
    {
        "name": "TalentBridge Zimbabwe",
        "service_focus": "Recruitment, talent management, and HR analytics training. Blended consulting and training model.",
        "pricing_notes": "HR workshops USD 150–350. Talent management programmes USD 400–800.",
        "strengths": "HR consulting credibility; growing talent management demand; practical case-study approach.",
        "weaknesses": "Dual model (consulting + training) dilutes training focus; small team.",
        "threat_level": 4.5,
        "market_share_estimate": 0.8,
    },
    {
        "name": "National Productivity Institute of Zimbabwe",
        "service_focus": "Lean management, productivity improvement, quality management (ISO), and operational excellence.",
        "pricing_notes": "Lean/ISO workshops USD 200–500. Productivity programmes USD 300–700.",
        "strengths": "Government productivity mandate; ISO alignment; growing manufacturing sector demand.",
        "weaknesses": "Underfunded government institution; limited marketing; small team.",
        "threat_level": 5.2,
        "market_share_estimate": 1.5,
    },
    {
        "name": "SADC Tribunal Training Secretariat (Zimbabwe node)",
        "service_focus": "Regional trade law, SADC protocol compliance, and cross-border legal training.",
        "pricing_notes": "Regional workshops USD 200–500.",
        "strengths": "Regional authority; legal sector credibility; growing cross-border trade demand.",
        "weaknesses": "Very niche legal/regional focus; limited programme frequency.",
        "threat_level": 3.1,
        "market_share_estimate": 0.3,
    },
    {
        "name": "Manica Road Business Training Centre",
        "service_focus": "Basic bookkeeping, tax returns, and QuickBooks training for SME owners in Harare CBD.",
        "pricing_notes": "Short courses USD 80–200.",
        "strengths": "CBD convenience; affordable; practical SME focus; growing SME market.",
        "weaknesses": "No accreditation; very small scale; limited to accounting basics.",
        "threat_level": 2.9,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Manicaland Institute of Technology",
        "service_focus": "Applied engineering, ICT, and business skills for Manicaland region.",
        "pricing_notes": "Certificate programmes USD 150–400.",
        "strengths": "Regional presence; HEXCO-eligible; practical focus; affordable.",
        "weaknesses": "New institution; limited brand recognition; small team.",
        "threat_level": 2.5,
        "market_share_estimate": 0.2,
    },
    {
        "name": "Chiredzi Technical College",
        "service_focus": "Agriculture, motor vehicle mechanics, and business basics for Lowveld region.",
        "pricing_notes": "HEXCO certificates USD 150–350.",
        "strengths": "Lowveld presence; agriculture-aligned; HEXCO-accredited.",
        "weaknesses": "Remote location; very small scale; limited corporate relevance.",
        "threat_level": 1.8,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Karoi Business College",
        "service_focus": "Business administration and agricultural business management in Mashonaland West.",
        "pricing_notes": "Certificate programmes USD 100–250.",
        "strengths": "Karoi agri-commercial market; affordable; local trust.",
        "weaknesses": "Very small; no accreditation; limited to basic business content.",
        "threat_level": 1.6,
        "market_share_estimate": 0.1,
    },
    {
        "name": "Zvishavane Community Training Centre",
        "service_focus": "Mining safety, basic business, and trades for Zvishavane mining community.",
        "pricing_notes": "Safety courses USD 80–200.",
        "strengths": "Mining community trust; local presence; safety training demand from mines.",
        "weaknesses": "Very small; limited to local mining community; no formal accreditation.",
        "threat_level": 1.5,
        "market_share_estimate": 0.1,
    },
]


class Command(BaseCommand):
    help = "Seed 100+ realistic Zimbabwean training institution competitors."

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete all existing Competitor records before seeding.",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            deleted, _ = Competitor.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Cleared {deleted} existing competitors."))

        created_count = 0
        skipped_count = 0

        for data in COMPETITORS:
            obj, created = Competitor.objects.get_or_create(
                name=data["name"],
                defaults={
                    "country": "Zimbabwe",
                    "service_focus": data["service_focus"],
                    "pricing_notes": data["pricing_notes"],
                    "strengths": data["strengths"],
                    "weaknesses": data["weaknesses"],
                    "threat_level": data["threat_level"],
                    "market_share_estimate": data.get("market_share_estimate"),
                },
            )
            if created:
                created_count += 1
            else:
                skipped_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Done — {created_count} competitors created, {skipped_count} already existed."
            )
        )
        self.stdout.write(
            self.style.SUCCESS(
                f"Total in DB: {Competitor.objects.count()} competitors."
            )
        )